//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLAzureMWUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLAzureMWUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding clustered index {0} on {1}.  You may want to change this index..
        /// </summary>
        internal static string AddingClusteredIndex {
            get {
                return ResourceManager.GetString("AddingClusteredIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLAzureMW has finished analysis.  Any issues discovered will be reported above..
        /// </summary>
        internal static string AnalysisComplete {
            get {
                return ResourceManager.GetString("AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appending script: {0} of {1}.
        /// </summary>
        internal static string AppendingScript {
            get {
                return ResourceManager.GetString("AppendingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Table - .
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure requires {0} extension on your user name.  Do you want me to add it for you?.
        /// </summary>
        internal static string AzureUserName {
            get {
                return ResourceManager.GetString("AzureUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure User Name Requirements.
        /// </summary>
        internal static string AzureUserNameWarning {
            get {
                return ResourceManager.GetString("AzureUserNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLAzureMW could not find the number of rows copied in the BCP output.  Here is the BCP command:.
        /// </summary>
        internal static string BCPCouldNotFind1 {
            get {
                return ResourceManager.GetString("BCPCouldNotFind1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the Regex string being looked for: .
        /// </summary>
        internal static string BCPExpectedRegexMatch {
            get {
                return ResourceManager.GetString("BCPExpectedRegexMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the BCP output:.
        /// </summary>
        internal static string BCPHereIsOutput {
            get {
                return ResourceManager.GetString("BCPHereIsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCP output was lost for command:
        ///
        ///{0}
        ///
        ///Data export was not completed for table {1}.  Please try again or use above command for manual export process..
        /// </summary>
        internal static string BCPMissingOutput {
            get {
                return ResourceManager.GetString("BCPMissingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access BCP output directory [{0}].
        /// </summary>
        internal static string BCPOutputDirectoryNotFound {
            get {
                return ResourceManager.GetString("BCPOutputDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCP output file: .
        /// </summary>
        internal static string BCPOutputFile {
            get {
                return ResourceManager.GetString("BCPOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of BCP output commands.
        /// </summary>
        internal static string BCPOutputSummary {
            get {
                return ResourceManager.GetString("BCPOutputSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCP upload process aborting ....
        /// </summary>
        internal static string BCPProcessAborting {
            get {
                return ResourceManager.GetString("BCPProcessAborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --&gt; Sorry, but BCP upload process failed:.
        /// </summary>
        internal static string BCPProcessFailed {
            get {
                return ResourceManager.GetString("BCPProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} out of {1}.
        /// </summary>
        internal static string BCPProcessingStatus {
            get {
                return ResourceManager.GetString("BCPProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0} of {1} ({2}%).
        /// </summary>
        internal static string BCPProcessingUpdate {
            get {
                return ResourceManager.GetString("BCPProcessingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --&gt; Failed to delete temp BCP file.  Error = {0}.
        /// </summary>
        internal static string BCPTempFileDeleteFailed {
            get {
                return ResourceManager.GetString("BCPTempFileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --&gt; Uploading data to {0}
        /// --&gt; BCP Command: {1}.
        /// </summary>
        internal static string BCPUploadingData {
            get {
                return ResourceManager.GetString("BCPUploadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCP upload command summary.
        /// </summary>
        internal static string BCPUploadSummary {
            get {
                return ResourceManager.GetString("BCPUploadSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using BCP to get data from table .
        /// </summary>
        internal static string BCPUsing {
            get {
                return ResourceManager.GetString("BCPUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing index {0}.{1} to a clustered index.  You may want to pick a different index to cluster on..
        /// </summary>
        internal static string ChangingClusteredIndex {
            get {
                return ResourceManager.GetString("ChangingClusteredIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a table.
        /// </summary>
        internal static string ChooseTable {
            get {
                return ResourceManager.GetString("ChooseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the &quot;Master DB&quot; to list all databases under the master data.
        ///Select &quot;Specify Database&quot; to work with only one database..
        /// </summary>
        internal static string DBConnect {
            get {
                return ResourceManager.GetString("DBConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that if you select &quot;Specify Database&quot;, you will not be able to
        ///create a new database or delete the one you are connect to..
        /// </summary>
        internal static string DBConnectWarningTarget {
            get {
                return ResourceManager.GetString("DBConnectWarningTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency file not found.  Error = {0}.
        /// </summary>
        internal static string DependencyCheckerFileNotFound {
            get {
                return ResourceManager.GetString("DependencyCheckerFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering: {0} of {1}.
        /// </summary>
        internal static string Discovering {
            get {
                return ResourceManager.GetString("Discovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --&gt; Error .
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ... .
        /// </summary>
        internal static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Configuration error ....
        /// </summary>
        internal static string ErrorApplicationConfiguration {
            get {
                return ResourceManager.GetString("ErrorApplicationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I can&apos;t find the proper language section in {0}.config
        ///for parsing BCP output.  Program can&apos;t proceed..
        /// </summary>
        internal static string ErrorLanguageSectionNotFound {
            get {
                return ResourceManager.GetString("ErrorLanguageSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the dependencies for {0} are missing.
        ///
        ///Error message = {1}..
        /// </summary>
        internal static string ErrorMissingDependencies {
            get {
                return ResourceManager.GetString("ErrorMissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --&gt; Error #: {0} -- {1}.
        /// </summary>
        internal static string ErrorNumAndMsg {
            get {
                return ResourceManager.GetString("ErrorNumAndMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing bcpArgs.
        /// </summary>
        internal static string ErrorParsingBCPArgs {
            get {
                return ResourceManager.GetString("ErrorParsingBCPArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1} member id = {2} range {3} .
        /// </summary>
        internal static string FederationMemberInfo {
            get {
                return ResourceManager.GetString("FederationMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Azure Federation objects are not supported in SQL Server.  Removed &apos;{0}&apos; statement on table {1}..
        /// </summary>
        internal static string FederationNotSupported {
            get {
                return ResourceManager.GetString("FederationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Keys ....
        /// </summary>
        internal static string ForiegnKeys {
            get {
                return ResourceManager.GetString("ForiegnKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I can&apos;t find the proper language section {0} in {1}.config
        ///for parsing BCP output.  Program can&apos;t proceed..
        /// </summary>
        internal static string LocalizedBCPCanNotFind {
            get {
                return ResourceManager.GetString("LocalizedBCPCanNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string MessageCanceled {
            get {
                return ResourceManager.GetString("MessageCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled processing at {0} ....
        /// </summary>
        internal static string MessageCanceledProcessing {
            get {
                return ResourceManager.GetString("MessageCanceledProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you have Specify Database checked and you must specify a database.
        /// </summary>
        internal static string MessageSpecifyDatabase {
            get {
                return ResourceManager.GetString("MessageSpecifyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Source Server.
        /// </summary>
        internal static string MessageTitleConnectSource {
            get {
                return ResourceManager.GetString("MessageTitleConnectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Target Server.
        /// </summary>
        internal static string MessageTitleConnectTarget {
            get {
                return ResourceManager.GetString("MessageTitleConnectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but user name is required.
        /// </summary>
        internal static string MessageUserName {
            get {
                return ResourceManager.GetString("MessageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --~----------------------------------------------------------------------------------------------------
        ///--~ Table {0} does not have a clustered index.
        ///--~ You will need to create a clustered index on this table before you will be able to insert data.
        ///--~----------------------------------------------------------------------------------------------------.
        /// </summary>
        internal static string NoClusteredIndex {
            get {
                return ResourceManager.GetString("NoClusteredIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} does not have a clustered index.
        ///You will need to create an clustered index before you will be able to enter data..
        /// </summary>
        internal static string NoClusteredIndex2 {
            get {
                return ResourceManager.GetString("NoClusteredIndex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected.
        /// </summary>
        internal static string NoDatabaseSelected {
            get {
                return ResourceManager.GetString("NoDatabaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} is a heap, and has no indexable columns.  You will need to add a clustered index before migrating this table..
        /// </summary>
        internal static string NoIndexableColumns {
            get {
                return ResourceManager.GetString("NoIndexableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL Servers found on the network!.
        /// </summary>
        internal static string NoSqlServers {
            get {
                return ResourceManager.GetString("NoSqlServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string ObjectTypeRoles {
            get {
                return ResourceManager.GetString("ObjectTypeRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        internal static string ObjectTypeSchemas {
            get {
                return ResourceManager.GetString("ObjectTypeSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        internal static string ObjectTypeStoredProcedures {
            get {
                return ResourceManager.GetString("ObjectTypeStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string ObjectTypeTables {
            get {
                return ResourceManager.GetString("ObjectTypeTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string ObjectTypeTriggers {
            get {
                return ResourceManager.GetString("ObjectTypeTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Functions.
        /// </summary>
        internal static string ObjectTypeUDF {
            get {
                return ResourceManager.GetString("ObjectTypeUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Data Types.
        /// </summary>
        internal static string ObjectTypeUDT {
            get {
                return ResourceManager.GetString("ObjectTypeUDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Table Types.
        /// </summary>
        internal static string ObjectTypeUDTT {
            get {
                return ResourceManager.GetString("ObjectTypeUDTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ObjectTypeViews {
            get {
                return ResourceManager.GetString("ObjectTypeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema Collections.
        /// </summary>
        internal static string ObjectTypeXMLSchemaCollections {
            get {
                return ResourceManager.GetString("ObjectTypeXMLSchemaCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Warning.
        /// </summary>
        internal static string PerformanceWarning {
            get {
                return ResourceManager.GetString("PerformanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is highly recommended at this time that you do not select &quot;Specify Database&quot; because of performance issues.
        ///
        ///Are you sure you need to do this?.
        /// </summary>
        internal static string PerformanceWarningAreYouSure {
            get {
                return ResourceManager.GetString("PerformanceWarningAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error #: {0} -- {1}
        ///{2}
        ///Process aborting at {3} ....
        /// </summary>
        internal static string ProcessAborting {
            get {
                return ResourceManager.GetString("ProcessAborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process canceled at {0} ....
        /// </summary>
        internal static string ProcessCanceledAt {
            get {
                return ResourceManager.GetString("ProcessCanceledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing finished at {0} -- UTC -&gt; {1}
        ///Total processing time: {2}.
        /// </summary>
        internal static string ProcessingFinished {
            get {
                return ResourceManager.GetString("ProcessingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started at {0} -- UTC -&gt; {1} ... .
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --~.
        /// </summary>
        internal static string RemoveComment {
            get {
                return ResourceManager.GetString("RemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~*/.
        /// </summary>
        internal static string RemoveCommentEnd {
            get {
                return ResourceManager.GetString("RemoveCommentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*~.
        /// </summary>
        internal static string RemoveCommentStart {
            get {
                return ResourceManager.GetString("RemoveCommentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Limit Exceeded.
        /// </summary>
        internal static string RetryLimitExceeded {
            get {
                return ResourceManager.GetString("RetryLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting: {0} of {1}.
        /// </summary>
        internal static string Scripting {
            get {
                return ResourceManager.GetString("Scripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting {0} ....
        /// </summary>
        internal static string ScriptingObj {
            get {
                return ResourceManager.GetString("ScriptingObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ScriptOptionsGeneral {
            get {
                return ResourceManager.GetString("ScriptOptionsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override: Perform All Compatibility Checks.
        /// </summary>
        internal static string ScriptOptionsOverride {
            get {
                return ResourceManager.GetString("ScriptOptionsOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override: Do Not Perform Compatibility Checks.
        /// </summary>
        internal static string ScriptOptionsOverrideNot {
            get {
                return ResourceManager.GetString("ScriptOptionsOverrideNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Only.
        /// </summary>
        internal static string ScriptOptionsTableData {
            get {
                return ResourceManager.GetString("ScriptOptionsTableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script table schema, data or both..
        /// </summary>
        internal static string ScriptOptionsTableDataDesc {
            get {
                return ResourceManager.GetString("ScriptOptionsTableDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Table / Data.
        /// </summary>
        internal static string ScriptOptionsTableDataDisplayName {
            get {
                return ResourceManager.GetString("ScriptOptionsTableDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Schema Only.
        /// </summary>
        internal static string ScriptOptionsTableSchema {
            get {
                return ResourceManager.GetString("ScriptOptionsTableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Schema with Data.
        /// </summary>
        internal static string ScriptOptionsTableSchemaData {
            get {
                return ResourceManager.GetString("ScriptOptionsTableSchemaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table/View Options.
        /// </summary>
        internal static string ScriptOptionsTableView {
            get {
                return ResourceManager.GetString("ScriptOptionsTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQL Compatibility Checks.
        /// </summary>
        internal static string ScriptOptionsTSQLCompatibility {
            get {
                return ResourceManager.GetString("ScriptOptionsTSQLCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Settings.
        /// </summary>
        internal static string ScriptOptionsUseDefault {
            get {
                return ResourceManager.GetString("ScriptOptionsUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s server name {0} should be {1}.  Do you want me to correct it for you?.
        /// </summary>
        internal static string ServerNamesDoNotMatch {
            get {
                return ResourceManager.GetString("ServerNamesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Azure.
        /// </summary>
        internal static string ServerType_SQLAzure {
            get {
                return ResourceManager.GetString("ServerType_SQLAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Azure Federation.
        /// </summary>
        internal static string ServerType_SQLAzureFed {
            get {
                return ResourceManager.GetString("ServerType_SQLAzureFed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        internal static string ServerType_SQLServer {
            get {
                return ResourceManager.GetString("ServerType_SQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the default values..
        /// </summary>
        internal static string SMOOptionsGeneralDefaults {
            get {
                return ResourceManager.GetString("SMOOptionsGeneralDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  not scripted.  Error message = {1}.
        /// </summary>
        internal static string SMOScriptingError {
            get {
                return ResourceManager.GetString("SMOScriptingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Stored Procedures..
        /// </summary>
        internal static string SOSADSPDesc {
            get {
                return ResourceManager.GetString("SOSADSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Stored Procedures.
        /// </summary>
        internal static string SOSADSPDisplayName {
            get {
                return ResourceManager.GetString("SOSADSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Agent Stored Procedures.
        /// </summary>
        internal static string SOSAgentSPDesc {
            get {
                return ResourceManager.GetString("SOSAgentSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Agent Stored Procedures.
        /// </summary>
        internal static string SOSAgentSPDisplayName {
            get {
                return ResourceManager.GetString("SOSAgentSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Agent Tables..
        /// </summary>
        internal static string SOSAgentTDesc {
            get {
                return ResourceManager.GetString("SOSAgentTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Agent Tables.
        /// </summary>
        internal static string SOSAgentTDisplayName {
            get {
                return ResourceManager.GetString("SOSAgentTDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and Restore Tables..
        /// </summary>
        internal static string SOSBackupRestoreDesc {
            get {
                return ResourceManager.GetString("SOSBackupRestoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and Restore Tables.
        /// </summary>
        internal static string SOSBackupRestoreDisplayName {
            get {
                return ResourceManager.GetString("SOSBackupRestoreDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Catalog Views..
        /// </summary>
        internal static string SOSCatalogVDesc {
            get {
                return ResourceManager.GetString("SOSCatalogVDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Catalog Views.
        /// </summary>
        internal static string SOSCatalogVDisplayName {
            get {
                return ResourceManager.GetString("SOSCatalogVDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Capture Stored Procedures..
        /// </summary>
        internal static string SOSCDCDesc {
            get {
                return ResourceManager.GetString("SOSCDCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Capture.
        /// </summary>
        internal static string SOSCDCDisplayName {
            get {
                return ResourceManager.GetString("SOSCDCDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Capture Tables..
        /// </summary>
        internal static string SOSCDCTDesc {
            get {
                return ResourceManager.GetString("SOSCDCTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Capture Tables.
        /// </summary>
        internal static string SOSCDCTDisplayName {
            get {
                return ResourceManager.GetString("SOSCDCTDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the check constraints for each table or view scripted..
        /// </summary>
        internal static string SOSCheckDesc {
            get {
                return ResourceManager.GetString("SOSCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Check Constraints.
        /// </summary>
        internal static string SOSCheckDisplayName {
            get {
                return ResourceManager.GetString("SOSCheckDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to override settings to force compatibility checks, ignor compatibility checks, or use indivual TSQL Check settings..
        /// </summary>
        internal static string SOSCompatibilityDesc {
            get {
                return ResourceManager.GetString("SOSCompatibilityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility Checks.
        /// </summary>
        internal static string SOSCompatibilityDisplayName {
            get {
                return ResourceManager.GetString("SOSCompatibilityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script CREATE.
        /// </summary>
        internal static string SOSCreate {
            get {
                return ResourceManager.GetString("SOSCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Controls..
        /// </summary>
        internal static string SOSDBDCDesc {
            get {
                return ResourceManager.GetString("SOSDBDCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Controls.
        /// </summary>
        internal static string SOSDBDCDisplayName {
            get {
                return ResourceManager.GetString("SOSDBDCDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Engine Stored Procedures..
        /// </summary>
        internal static string SOSDBEngineSPDesc {
            get {
                return ResourceManager.GetString("SOSDBEngineSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Engine Stored Procedures.
        /// </summary>
        internal static string SOSDBEngineSPDisplayName {
            get {
                return ResourceManager.GetString("SOSDBEngineSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Mail Stored Procedures..
        /// </summary>
        internal static string SOSDBMailSPDesc {
            get {
                return ResourceManager.GetString("SOSDBMailSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Mail Stored Procedures.
        /// </summary>
        internal static string SOSDBMailSPDisplayName {
            get {
                return ResourceManager.GetString("SOSDBMailSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Maintenance Plans..
        /// </summary>
        internal static string SOSDBMaintDesc {
            get {
                return ResourceManager.GetString("SOSDBMaintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Maintenance Plans.
        /// </summary>
        internal static string SOSDBMaintDisplayName {
            get {
                return ResourceManager.GetString("SOSDBMaintDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Defaults.
        /// </summary>
        internal static string SOSDefaults {
            get {
                return ResourceManager.GetString("SOSDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the default values..
        /// </summary>
        internal static string SOSDefaultsDesc {
            get {
                return ResourceManager.GetString("SOSDefaultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed Queries Stored Procedures..
        /// </summary>
        internal static string SOSDQSPDesc {
            get {
                return ResourceManager.GetString("SOSDQSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed Queries Stored Procedures.
        /// </summary>
        internal static string SOSDQSPDisplayName {
            get {
                return ResourceManager.GetString("SOSDQSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script DROP.
        /// </summary>
        internal static string SOSDrop {
            get {
                return ResourceManager.GetString("SOSDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script DROP and CREATE.
        /// </summary>
        internal static string SOSDropCreate {
            get {
                return ResourceManager.GetString("SOSDropCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Object CREATE / DROP Statements..
        /// </summary>
        internal static string SOSDropCreateDesc {
            get {
                return ResourceManager.GetString("SOSDropCreateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the foreign keys for each table scripted..
        /// </summary>
        internal static string SOSForeignKeysDesc {
            get {
                return ResourceManager.GetString("SOSForeignKeysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Foreign Keys.
        /// </summary>
        internal static string SOSForeignKeysDisplayName {
            get {
                return ResourceManager.GetString("SOSForeignKeysDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Search Stored Procedures..
        /// </summary>
        internal static string SOSFTSSPDesc {
            get {
                return ResourceManager.GetString("SOSFTSSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Search Stored Procedures.
        /// </summary>
        internal static string SOSFTSSPDisplayName {
            get {
                return ResourceManager.GetString("SOSFTSSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Extended Stored Procedures..
        /// </summary>
        internal static string SOSGenExtSPDesc {
            get {
                return ResourceManager.GetString("SOSGenExtSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Extended Stored Procedures.
        /// </summary>
        internal static string SOSGenExtSPDisplayName {
            get {
                return ResourceManager.GetString("SOSGenExtSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General TSQL checks (Recommended)..
        /// </summary>
        internal static string SOSGenTSQLDesc {
            get {
                return ResourceManager.GetString("SOSGenTSQLDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General TSQL.
        /// </summary>
        internal static string SOSGenTSQLDisplayName {
            get {
                return ResourceManager.GetString("SOSGenTSQLDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Headers.
        /// </summary>
        internal static string SOSHeaders {
            get {
                return ResourceManager.GetString("SOSHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include descriptive headers for each object scripted..
        /// </summary>
        internal static string SOSHeadersDesc {
            get {
                return ResourceManager.GetString("SOSHeadersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the check constraints for each table or view scripted..
        /// </summary>
        internal static string SOSIndexesDesc {
            get {
                return ResourceManager.GetString("SOSIndexesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Indexes.
        /// </summary>
        internal static string SOSIndexesDisplayName {
            get {
                return ResourceManager.GetString("SOSIndexesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Services Tables..
        /// </summary>
        internal static string SOSISTDesc {
            get {
                return ResourceManager.GetString("SOSISTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Services Tables.
        /// </summary>
        internal static string SOSISTDisplayName {
            get {
                return ResourceManager.GetString("SOSISTDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Shipping..
        /// </summary>
        internal static string SOSLSDesc {
            get {
                return ResourceManager.GetString("SOSLSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Shipping.
        /// </summary>
        internal static string SOSLSDisplayName {
            get {
                return ResourceManager.GetString("SOSLSDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Mail Stored Procedures..
        /// </summary>
        internal static string SOSMailSPDesc {
            get {
                return ResourceManager.GetString("SOSMailSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Mail Stored Procedures.
        /// </summary>
        internal static string SOSMailSPDisplayName {
            get {
                return ResourceManager.GetString("SOSMailSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Functions..
        /// </summary>
        internal static string SOSMFDesc {
            get {
                return ResourceManager.GetString("SOSMFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Functions.
        /// </summary>
        internal static string SOSMFDisplayName {
            get {
                return ResourceManager.GetString("SOSMFDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include If Not Exists.
        /// </summary>
        internal static string SOSNotExists {
            get {
                return ResourceManager.GetString("SOSNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the objects that have the IF NOT EXISTS option..
        /// </summary>
        internal static string SOSNotExistsDesc {
            get {
                return ResourceManager.GetString("SOSNotExistsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLEDB Tables..
        /// </summary>
        internal static string SOSOLEDBDesc {
            get {
                return ResourceManager.GetString("SOSOLEDBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLEDB Tables.
        /// </summary>
        internal static string SOSOLEDBDisplayName {
            get {
                return ResourceManager.GetString("SOSOLEDBDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLE Automation Stored Procedures..
        /// </summary>
        internal static string SOSOLESPDesc {
            get {
                return ResourceManager.GetString("SOSOLESPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLE Automation Stored Procedures.
        /// </summary>
        internal static string SOSOLESPDisplayName {
            get {
                return ResourceManager.GetString("SOSOLESPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the primary keys for each table scripted..
        /// </summary>
        internal static string SOSPrimaryKeysDesc {
            get {
                return ResourceManager.GetString("SOSPrimaryKeysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Primary Keys.
        /// </summary>
        internal static string SOSPrimaryKeysDisplayName {
            get {
                return ResourceManager.GetString("SOSPrimaryKeysDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiler Stored Procedures..
        /// </summary>
        internal static string SOSProfilerSPDesc {
            get {
                return ResourceManager.GetString("SOSProfilerSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiler Stored Procedures.
        /// </summary>
        internal static string SOSProfilerSPDisplayName {
            get {
                return ResourceManager.GetString("SOSProfilerSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Stored Procedures.
        /// </summary>
        internal static string SOSReplSPDesc {
            get {
                return ResourceManager.GetString("SOSReplSPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Stored Procedures.
        /// </summary>
        internal static string SOSReplSPDisplayName {
            get {
                return ResourceManager.GetString("SOSReplSPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Tables..
        /// </summary>
        internal static string SOSReplTabDesc {
            get {
                return ResourceManager.GetString("SOSReplTabDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Tables.
        /// </summary>
        internal static string SOSReplTabDisplayName {
            get {
                return ResourceManager.GetString("SOSReplTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowset Functions..
        /// </summary>
        internal static string SOSRowsetDesc {
            get {
                return ResourceManager.GetString("SOSRowsetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowset Functions.
        /// </summary>
        internal static string SOSRowsetDisplayName {
            get {
                return ResourceManager.GetString("SOSRowsetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Collation..
        /// </summary>
        internal static string SOSScriptCollationDesc {
            get {
                return ResourceManager.GetString("SOSScriptCollationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Collation.
        /// </summary>
        internal static string SOSScriptCollationDisplayName {
            get {
                return ResourceManager.GetString("SOSScriptCollationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Functions..
        /// </summary>
        internal static string SOSSecurityDesc {
            get {
                return ResourceManager.GetString("SOSSecurityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Functions.
        /// </summary>
        internal static string SOSSecurityDisplayName {
            get {
                return ResourceManager.GetString("SOSSecurityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Stored Procedures..
        /// </summary>
        internal static string SOSSecuritySPDesc {
            get {
                return ResourceManager.GetString("SOSSecuritySPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Stored Procedures.
        /// </summary>
        internal static string SOSSecuritySPDisplayName {
            get {
                return ResourceManager.GetString("SOSSecuritySPDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Functions..
        /// </summary>
        internal static string SOSSysFunDesc {
            get {
                return ResourceManager.GetString("SOSSysFunDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Functions.
        /// </summary>
        internal static string SOSSysFunDisplayName {
            get {
                return ResourceManager.GetString("SOSSysFunDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Statistical Functions..
        /// </summary>
        internal static string SOSSysStatDesc {
            get {
                return ResourceManager.GetString("SOSSysStatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Statistical Functions.
        /// </summary>
        internal static string SOSSysStatDisplayName {
            get {
                return ResourceManager.GetString("SOSSysStatDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the triggers for each table scripted..
        /// </summary>
        internal static string SOSTriggersDesc {
            get {
                return ResourceManager.GetString("SOSTriggersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Table Triggers.
        /// </summary>
        internal static string SOSTriggersDisplayName {
            get {
                return ResourceManager.GetString("SOSTriggersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified..
        /// </summary>
        internal static string SOSUnclassifiedDesc {
            get {
                return ResourceManager.GetString("SOSUnclassifiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified.
        /// </summary>
        internal static string SOSUnclassifiedDisplayName {
            get {
                return ResourceManager.GetString("SOSUnclassifiedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script the unique keys for each table scripted..
        /// </summary>
        internal static string SOSUniqueKeysDesc {
            get {
                return ResourceManager.GetString("SOSUniqueKeysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Unique Keys.
        /// </summary>
        internal static string SOSUniqueKeysDisplayName {
            get {
                return ResourceManager.GetString("SOSUniqueKeysDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.windows.net.
        /// </summary>
        internal static string SQLAzureCloudName {
            get {
                return ResourceManager.GetString("SQLAzureCloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has received a severity {1}, state {2} error number {3}
        ///on line {4} of procedure {5} on server {6}:
        ///{7}.
        /// </summary>
        internal static string SqlError {
            get {
                return ResourceManager.GetString("SqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid parameter name on the parameter #{0}, the ParameterName property has the following value: &apos;{1}&apos;..
        /// </summary>
        internal static string SqlHelperValidParameter {
            get {
                return ResourceManager.GetString("SqlHelperValidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State changed from {0} to {1}.
        /// </summary>
        internal static string StateChanged {
            get {
                return ResourceManager.GetString("StateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- Success:.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Server.
        /// </summary>
        internal static string TargetServer {
            get {
                return ResourceManager.GetString("TargetServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target server.
        /// </summary>
        internal static string TargetServerDesc {
            get {
                return ResourceManager.GetString("TargetServerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour, .
        /// </summary>
        internal static string TimeHour {
            get {
                return ResourceManager.GetString("TimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours, .
        /// </summary>
        internal static string TimeHours {
            get {
                return ResourceManager.GetString("TimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute and .
        /// </summary>
        internal static string TimeMinute {
            get {
                return ResourceManager.GetString("TimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes and .
        /// </summary>
        internal static string TimeMinutes {
            get {
                return ResourceManager.GetString("TimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  second.
        /// </summary>
        internal static string TimeSecond {
            get {
                return ResourceManager.GetString("TimeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace File Line # {0} : .
        /// </summary>
        internal static string TraceFileLine {
            get {
                return ResourceManager.GetString("TraceFileLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Note that User Defined Types are currently not supported in SQL Azure.
        /// </summary>
        internal static string UDTNotSupported {
            get {
                return ResourceManager.GetString("UDTNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Types are currently not supported in SQL Azure.
        /// </summary>
        internal static string UDTNotSupported1 {
            get {
                return ResourceManager.GetString("UDTNotSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Types are currently not supported in SQL Azure
        ///The following User Defined Types were found:.
        /// </summary>
        internal static string UDTNotSupported2 {
            get {
                return ResourceManager.GetString("UDTNotSupported2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Process.
        /// </summary>
        internal static string WizardAction {
            get {
                return ResourceManager.GetString("WizardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selelect the process you want the wizard to talk you through..
        /// </summary>
        internal static string WizardActionDesc {
            get {
                return ResourceManager.GetString("WizardActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Objects.
        /// </summary>
        internal static string WizardActionObjectTypes {
            get {
                return ResourceManager.GetString("WizardActionObjectTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database objects to script.
        /// </summary>
        internal static string WizardActionObjectTypesDesc {
            get {
                return ResourceManager.GetString("WizardActionObjectTypesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Summary.
        /// </summary>
        internal static string WizardActionResultsSummary {
            get {
                return ResourceManager.GetString("WizardActionResultsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting and Analysis Summary.
        /// </summary>
        internal static string WizardActionResultsSummaryDesc {
            get {
                return ResourceManager.GetString("WizardActionResultsSummaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Script Options.
        /// </summary>
        internal static string WizardActionScriptingOptions {
            get {
                return ResourceManager.GetString("WizardActionScriptingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the options for the objects you want to script..
        /// </summary>
        internal static string WizardActionScriptingOptionsDesc {
            get {
                return ResourceManager.GetString("WizardActionScriptingOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Wizard Summary.
        /// </summary>
        internal static string WizardActionScriptWizardSummary {
            get {
                return ResourceManager.GetString("WizardActionScriptWizardSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your selections for the wizard..
        /// </summary>
        internal static string WizardActionScriptWizardSummaryDesc {
            get {
                return ResourceManager.GetString("WizardActionScriptWizardSummaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source.
        /// </summary>
        internal static string WizardActionSelectSource {
            get {
                return ResourceManager.GetString("WizardActionSelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source you want to script..
        /// </summary>
        internal static string WizardActionSelectSourceDesc {
            get {
                return ResourceManager.GetString("WizardActionSelectSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Target Server Connection.
        /// </summary>
        internal static string WizardActionSetupTargetConnection {
            get {
                return ResourceManager.GetString("WizardActionSetupTargetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information for connection to Target Server..
        /// </summary>
        internal static string WizardActionSetupTargetConnectionDesc {
            get {
                return ResourceManager.GetString("WizardActionSetupTargetConnectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Server Response.
        /// </summary>
        internal static string WizardActionTargetResults {
            get {
                return ResourceManager.GetString("WizardActionTargetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from TSQL against Target Server.
        /// </summary>
        internal static string WizardActionTargetResultsDesc {
            get {
                return ResourceManager.GetString("WizardActionTargetResultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Note that XML Schema Collections are currently not supported in SQL Azure
        ///** You will need to modify your tables to just store XML in a varchar(max) type column
        ///** and adjust yor program accordingly..
        /// </summary>
        internal static string XMLSchemaCollectionNotSupported {
            get {
                return ResourceManager.GetString("XMLSchemaCollectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema Collections are currently not supported in SQL Azure.
        /// </summary>
        internal static string XMLSchemaCollectionNotSupported1 {
            get {
                return ResourceManager.GetString("XMLSchemaCollectionNotSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema Collections are currently not supported in SQL Azure
        ///The following XML Schema Collections were found:.
        /// </summary>
        internal static string XMLSchemaCollectionNotSupported2 {
            get {
                return ResourceManager.GetString("XMLSchemaCollectionNotSupported2", resourceCulture);
            }
        }
    }
}
