//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLAzureMWBatchBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLAzureMWBatchBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access BCP output directory [{0}].
        /// </summary>
        internal static string BCPOutputDirectoryNotFound {
            get {
                return ResourceManager.GetString("BCPOutputDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, error opening output file {0}.  Error: {1}.
        /// </summary>
        internal static string ErrorOpeningFile {
            get {
                return ResourceManager.GetString("ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DROP scripts ....
        /// </summary>
        internal static string MessageCreatingDropScripts {
            get {
                return ResourceManager.GetString("MessageCreatingDropScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analysis done on script.
        ///Processing finished at {0} -- UTC -&gt; {1}
        ///Total processing time: {2}.
        /// </summary>
        internal static string MessageFinishedNoAnalysis {
            get {
                return ResourceManager.GetString("MessageFinishedNoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed at {0} -- UTC -&gt; {1}
        ///Any issues discovered will be reported above.
        ///Total processing time: {2}.
        /// </summary>
        internal static string MessageFinishedWithAnalysis {
            get {
                return ResourceManager.GetString("MessageFinishedWithAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour, .
        /// </summary>
        internal static string MessageHour {
            get {
                return ResourceManager.GetString("MessageHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours, .
        /// </summary>
        internal static string MessageHours {
            get {
                return ResourceManager.GetString("MessageHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute and .
        /// </summary>
        internal static string MessageMinute {
            get {
                return ResourceManager.GetString("MessageMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes and .
        /// </summary>
        internal static string MessageMinutes {
            get {
                return ResourceManager.GetString("MessageMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started at {0} -- UTC -&gt; {1} ... .
        /// </summary>
        internal static string MessageProcessStarted {
            get {
                return ResourceManager.GetString("MessageProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  second.
        /// </summary>
        internal static string MessageSecond {
            get {
                return ResourceManager.GetString("MessageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string MessageSeconds {
            get {
                return ResourceManager.GetString("MessageSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting objects by dependency ....
        /// </summary>
        internal static string MessageSorting {
            get {
                return ResourceManager.GetString("MessageSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string ObjectTypeRoles {
            get {
                return ResourceManager.GetString("ObjectTypeRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        internal static string ObjectTypeSchemas {
            get {
                return ResourceManager.GetString("ObjectTypeSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        internal static string ObjectTypeStoredProcedures {
            get {
                return ResourceManager.GetString("ObjectTypeStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string ObjectTypeTables {
            get {
                return ResourceManager.GetString("ObjectTypeTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string ObjectTypeTriggers {
            get {
                return ResourceManager.GetString("ObjectTypeTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Data Types.
        /// </summary>
        internal static string ObjectTypeUDT {
            get {
                return ResourceManager.GetString("ObjectTypeUDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Table Types.
        /// </summary>
        internal static string ObjectTypeUDTT {
            get {
                return ResourceManager.GetString("ObjectTypeUDTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema Collections.
        /// </summary>
        internal static string ObjectTypeXMLSchemaCollections {
            get {
                return ResourceManager.GetString("ObjectTypeXMLSchemaCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All parameters for SQLAzureMWBatchBackup can be found in the config file.
        ///
        ///If you want, you can override the config file by specifying the parameters you want to override.
        ///
        ///usage: SQLAzureMWBatchBackup -S server -U username -P password -D Northwind
        ///
        ///[-a {true or false} append datetime folder to output directory]
        ///[-S source server name]
        ///[-U username]
        ///[-P password]
        ///[-D source database name]
        ///[-o output file]
        ///[-O output directory for all files]
        ///[-T trusted connection]
        ///
        ///Note that the above args ov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramArgs {
            get {
                return ResourceManager.GetString("ProgramArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Version {1}.
        /// </summary>
        internal static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
